import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


/*
* 폴더명 구조
* 폴더 구조 처음에 잘 짜야 됩니다.
*   로그인 전 / 로그인 후
*   가장 큰 개념을 시작으로 구조를 짜기 시작합니다.
*
* [] : 대괄호 - url에 관여를 하지만 이름이 변경될 수 있는 폴더명 ( 예시 : user이름 )
* () : 소괄호 - url에 관여를 안하지만 그룹을 지을 수 있는 폴더명 ( 예시 : login 전 login 후 )
*
*
* template.tsx : 새로운 데이터를 가져올 때 마운트가 되는 페이지명
* layout.tsx : 리 렌더링, 데이터를 다시 가져오지 않는 페이지명
* */


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className={styles.container}>
          {children}
        </div>
      </body>
    </html>
  );
}
